SET DEFINE OFF;

-- FINASANGRE ORDS personalizado.
-- Ejecutar completo con F5 / Run Script en Oracle SQL Developer o APEX SQL Worksheet.

CREATE OR REPLACE FUNCTION fn_finasangre_json_escape(p_text IN VARCHAR2)
RETURN VARCHAR2
IS
BEGIN
  RETURN REPLACE(
           REPLACE(
             REPLACE(
               REPLACE(NVL(p_text, ''), '\', '\\'),
               '"', '\"'
             ),
             CHR(10), ' '
           ),
           CHR(13), ' '
         );
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~
    CREATE TABLE auditoria_finasangre (
      id_auditoria   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      id_usuario     NUMBER,
      accion         VARCHAR2(80) NOT NULL,
      modulo         VARCHAR2(80) NOT NULL,
      detalle        CLOB,
      fecha_evento   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~
    CREATE TABLE reportes_mensuales_finasangre (
      id_reporte        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      id_herrador       NUMBER NULL,
      periodo_inicio    DATE NOT NULL,
      periodo_fin       DATE NOT NULL,
      mes               NUMBER(2) NOT NULL,
      anio              NUMBER(4) NOT NULL,
      total_herrajes    NUMBER DEFAULT 0 NOT NULL,
      pdf_url           VARCHAR2(1000),
      enviado_whatsapp  VARCHAR2(2) DEFAULT 'NO' NOT NULL,
      enviado_correo    VARCHAR2(2) DEFAULT 'NO' NOT NULL,
      fecha_envio       DATE,
      estado            VARCHAR2(30) DEFAULT 'GENERADO' NOT NULL,
      tipo_reporte      VARCHAR2(20) DEFAULT 'HERRADOR' NOT NULL,
      fecha_creacion    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~
    CREATE TABLE aura_finasangre (
      id_aura        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      id_usuario     NUMBER,
      tipo           VARCHAR2(30),
      mensaje        CLOB,
      respuesta      CLOB,
      contexto       VARCHAR2(50),
      id_referencia  NUMBER,
      fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ~';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

DECLARE
  PROCEDURE add_col(p_table VARCHAR2, p_col VARCHAR2, p_sql VARCHAR2) IS
    l_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO l_count
      FROM user_tab_columns
     WHERE table_name = UPPER(p_table)
       AND column_name = UPPER(p_col);

    IF l_count = 0 THEN
      EXECUTE IMMEDIATE p_sql;
    END IF;
  END;
BEGIN
  add_col('REPORTES_MENSUALES_FINASANGRE', 'TIPO_REPORTE',
    'ALTER TABLE reportes_mensuales_finasangre ADD tipo_reporte VARCHAR2(20) DEFAULT ''HERRADOR'' NOT NULL');
  add_col('REPORTES_MENSUALES_FINASANGRE', 'FECHA_CREACION',
    'ALTER TABLE reportes_mensuales_finasangre ADD fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL');
  add_col('REPORTES_MENSUALES_FINASANGRE', 'FECHA_ENVIO',
    'ALTER TABLE reportes_mensuales_finasangre ADD fecha_envio DATE');
  add_col('CABALLOS_FINASANGRE', 'FOTO_URL',
    'ALTER TABLE caballos_finasangre ADD foto_url VARCHAR2(1000)');
  add_col('HERRAJES_FINASANGRE', 'FOTO_ANTES_URL',
    'ALTER TABLE herrajes_finasangre ADD foto_antes_url VARCHAR2(1000)');
  add_col('HERRAJES_FINASANGRE', 'FOTO_DESPUES_URL',
    'ALTER TABLE herrajes_finasangre ADD foto_despues_url VARCHAR2(1000)');
  add_col('HERRAJES_FINASANGRE', 'OBSERVACIONES',
    'ALTER TABLE herrajes_finasangre ADD observaciones CLOB');
END;
/

BEGIN
  ORDS.ENABLE_OBJECT(
    p_enabled        => TRUE,
    p_schema         => USER,
    p_object         => 'AURA_FINASANGRE',
    p_object_type    => 'TABLE',
    p_object_alias   => 'aura_finasangre',
    p_auto_rest_auth => FALSE
  );
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
  ORDS.ENABLE_OBJECT(
    p_enabled        => TRUE,
    p_schema         => USER,
    p_object         => 'REPORTES_MENSUALES_FINASANGRE',
    p_object_type    => 'TABLE',
    p_object_alias   => 'reportes_mensuales_finasangre',
    p_auto_rest_auth => FALSE
  );
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
  ORDS.ENABLE_OBJECT(
    p_enabled        => TRUE,
    p_schema         => USER,
    p_object         => 'AUDITORIA_FINASANGRE',
    p_object_type    => 'TABLE',
    p_object_alias   => 'auditoria_finasangre',
    p_auto_rest_auth => FALSE
  );
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_protect_owner';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4080 THEN
      NULL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_protect_owner_update
BEFORE UPDATE ON usuarios_finasangre
FOR EACH ROW
BEGIN
  IF LOWER(:OLD.email) = 'abrahambc' THEN
    IF LOWER(:NEW.email) <> 'abrahambc'
       OR UPPER(NVL(:NEW.rol, '')) <> 'OWNER'
       OR UPPER(NVL(:NEW.activo, '')) <> 'SI' THEN
      RAISE_APPLICATION_ERROR(-20030, 'No se puede modificar, desactivar ni quitar rol OWNER a abrahambc.');
    END IF;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_protect_owner_delete
BEFORE DELETE ON usuarios_finasangre
FOR EACH ROW
BEGIN
  IF LOWER(:OLD.email) = 'abrahambc' THEN
    RAISE_APPLICATION_ERROR(-20031, 'No se puede eliminar el OWNER abrahambc.');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_herraje_auto
BEFORE INSERT OR UPDATE ON herrajes_finasangre
FOR EACH ROW
BEGIN
  IF :NEW.fecha_herraje IS NULL THEN
    :NEW.fecha_herraje := SYSDATE;
  END IF;

  :NEW.dia := TO_NUMBER(TO_CHAR(:NEW.fecha_herraje, 'DD'));
  :NEW.mes := TO_NUMBER(TO_CHAR(:NEW.fecha_herraje, 'MM'));
  :NEW.anio := TO_NUMBER(TO_CHAR(:NEW.fecha_herraje, 'YYYY'));
  :NEW.hora := TO_CHAR(:NEW.fecha_herraje, 'HH24:MI');
END;
/

CREATE OR REPLACE PROCEDURE prc_delete_caballo_finasangre(
  p_id_caballo     IN NUMBER,
  p_delete_history IN VARCHAR2 DEFAULT 'NO'
) AS
  l_count   NUMBER;
  l_deleted NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM herrajes_finasangre
   WHERE id_caballo = p_id_caballo;

  IF UPPER(NVL(p_delete_history, 'NO')) = 'SI' THEN
    DELETE FROM herrajes_finasangre WHERE id_caballo = p_id_caballo;
    DELETE FROM caballos_finasangre WHERE id_caballo = p_id_caballo;
    l_deleted := SQL%ROWCOUNT;
  ELSE
    IF l_count > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar porque tiene herrajes asociados.');
    END IF;

    DELETE FROM caballos_finasangre WHERE id_caballo = p_id_caballo;
    l_deleted := SQL%ROWCOUNT;
  END IF;

  IF l_deleted = 0 THEN
    RAISE_APPLICATION_ERROR(-20002, 'Caballo no encontrado.');
  END IF;
END;
/

CREATE OR REPLACE PROCEDURE prc_generar_reportes_mensuales_fin AS
  l_inicio DATE := TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM');
  l_fin    DATE := LAST_DAY(ADD_MONTHS(SYSDATE, -1));
  l_mes    NUMBER := EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE, -1));
  l_anio   NUMBER := EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -1));

  PROCEDURE ensure_reporte(p_id_herrador NUMBER, p_tipo VARCHAR2) IS
    l_count NUMBER;
    l_total NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO l_count
      FROM reportes_mensuales_finasangre
     WHERE mes = l_mes
       AND anio = l_anio
       AND tipo_reporte = p_tipo
       AND NVL(id_herrador, -1) = NVL(p_id_herrador, -1);

    IF l_count = 0 THEN
      SELECT COUNT(*)
        INTO l_total
        FROM herrajes_finasangre
       WHERE TRUNC(NVL(
               fecha_herraje,
               CASE
                 WHEN anio > 0 AND mes > 0 AND dia > 0
                 THEN TO_DATE(anio || '-' || mes || '-' || dia, 'YYYY-MM-DD')
               END
             )) BETWEEN l_inicio AND l_fin
         AND (p_id_herrador IS NULL OR id_herrador = p_id_herrador);

      INSERT INTO reportes_mensuales_finasangre (
        id_herrador, periodo_inicio, periodo_fin, mes, anio,
        total_herrajes, pdf_url, enviado_whatsapp, enviado_correo,
        estado, tipo_reporte, fecha_creacion
      ) VALUES (
        p_id_herrador, l_inicio, l_fin, l_mes, l_anio,
        l_total, NULL, 'NO', 'NO',
        'GENERADO', p_tipo, SYSTIMESTAMP
      );
    END IF;
  END;
BEGIN
  FOR h IN (
    SELECT id_herrador
      FROM herradores_finasangre
     WHERE NVL(activo, 'SI') = 'SI'
  ) LOOP
    ensure_reporte(h.id_herrador, 'HERRADOR');
  END LOOP;

  ensure_reporte(NULL, 'GLOBAL');
END;
/

BEGIN
  DBMS_SCHEDULER.DROP_JOB('JOB_GENERAR_REPORTES_MENSUALES_FIN', TRUE);
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
  DBMS_SCHEDULER.CREATE_JOB(
    job_name        => 'JOB_GENERAR_REPORTES_MENSUALES_FIN',
    job_type        => 'STORED_PROCEDURE',
    job_action      => 'PRC_GENERAR_REPORTES_MENSUALES_FIN',
    start_date      => TO_TIMESTAMP_TZ(
                         TO_CHAR(TRUNC(SYSTIMESTAMP, 'MM') + INTERVAL '1' MONTH, 'YYYY-MM-DD')
                         || ' 08:00:00 America/Santiago',
                         'YYYY-MM-DD HH24:MI:SS TZR'
                       ),
    repeat_interval => 'FREQ=MONTHLY;BYMONTHDAY=1;BYHOUR=8;BYMINUTE=0;BYSECOND=0',
    enabled         => TRUE,
    comments        => 'Genera reportes mensuales FINASANGRE el dia 1 a las 08:00 America/Santiago'
  );
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
  ORDS.DELETE_MODULE(p_module_name => 'finasangre');
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
  ORDS.DEFINE_MODULE(
    p_module_name    => 'finasangre',
    p_base_path      => '/finasangre/',
    p_items_per_page => 100
  );
END;
/

BEGIN
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'caballos');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'caballos/:id');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'corrales');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'corrales/:id');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'preparadores');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'preparadores/:id');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'herradores');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'herradores/:id');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'herrajes');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'herrajes/:id');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'usuarios');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'usuarios/:id');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'suscripciones');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'suscripciones/:id');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'reportes');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'reportes/generar');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'reportes/generar-todos');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'aura_finasangre');
  ORDS.DEFINE_TEMPLATE(p_module_name => 'finasangre', p_pattern => 'aura_finasangre/limpiar');
END;
/

BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'caballos',
    p_method      => 'GET',
    p_source_type => 'json/query',
    p_source      => 'SELECT * FROM caballos_finasangre ORDER BY nombre_caballo'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'caballos/:id',
    p_method      => 'GET',
    p_source_type => 'json/item',
    p_source      => 'SELECT * FROM caballos_finasangre WHERE id_caballo = :id'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'caballos',
    p_method      => 'POST',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  INSERT INTO caballos_finasangre (
    nombre_caballo, edad, fecha_nacimiento, id_corral, id_preparador,
    sexo, color, activo, foto_url
  ) VALUES (
    :nombre_caballo, :edad,
    CASE
      WHEN :fecha_nacimiento IS NULL THEN NULL
      ELSE TO_DATE(SUBSTR(:fecha_nacimiento, 1, 10), 'YYYY-MM-DD')
    END,
    :id_corral, :id_preparador, :sexo, :color, NVL(:activo, 'SI'), :foto_url
  );
  :status_code := 201;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'caballos/:id',
    p_method      => 'PUT',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  UPDATE caballos_finasangre
     SET nombre_caballo = :nombre_caballo,
         edad = :edad,
         fecha_nacimiento = CASE
           WHEN :fecha_nacimiento IS NULL THEN NULL
           ELSE TO_DATE(SUBSTR(:fecha_nacimiento, 1, 10), 'YYYY-MM-DD')
         END,
         id_corral = :id_corral,
         id_preparador = :id_preparador,
         sexo = :sexo,
         color = :color,
         activo = NVL(:activo, activo),
         foto_url = :foto_url
   WHERE id_caballo = :id;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'caballos/:id',
    p_method      => 'DELETE',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  PRC_DELETE_CABALLO_FINASANGRE(:id, NVL(:delete_history, 'NO'));
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );
END;
/

BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'corrales',
    p_method      => 'GET',
    p_source_type => 'json/query',
    p_source      => 'SELECT * FROM corrales_finasangre ORDER BY numero_corral'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'corrales',
    p_method      => 'POST',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  INSERT INTO corrales_finasangre (numero_corral, nombre_corral, ubicacion, capacidad, activo)
  VALUES (:numero_corral, :nombre_corral, :ubicacion, :capacidad, NVL(:activo, 'SI'));
  :status_code := 201;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'corrales/:id',
    p_method      => 'PUT',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  UPDATE corrales_finasangre
     SET numero_corral = :numero_corral,
         nombre_corral = :nombre_corral,
         ubicacion = :ubicacion,
         capacidad = :capacidad,
         activo = NVL(:activo, activo)
   WHERE id_corral = :id;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'corrales/:id',
    p_method      => 'DELETE',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  DELETE FROM corrales_finasangre WHERE id_corral = :id;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );
END;
/

BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'preparadores',
    p_method      => 'GET',
    p_source_type => 'json/query',
    p_source      => 'SELECT * FROM preparadores_finasangre ORDER BY nombre_completo'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'preparadores',
    p_method      => 'POST',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  INSERT INTO preparadores_finasangre (nombre_completo, telefono, email, activo)
  VALUES (:nombre_completo, :telefono, LOWER(:email), NVL(:activo, 'SI'));
  :status_code := 201;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'preparadores/:id',
    p_method      => 'PUT',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  UPDATE preparadores_finasangre
     SET nombre_completo = :nombre_completo,
         telefono = :telefono,
         email = LOWER(:email),
         activo = NVL(:activo, activo)
   WHERE id_preparador = :id;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'preparadores/:id',
    p_method      => 'DELETE',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  DELETE FROM preparadores_finasangre WHERE id_preparador = :id;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );
END;
/

BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'herradores',
    p_method      => 'GET',
    p_source_type => 'json/query',
    p_source      => 'SELECT * FROM herradores_finasangre ORDER BY nombre_completo'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'herradores',
    p_method      => 'POST',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  INSERT INTO herradores_finasangre (id_usuario, codigo_herrador, nombre_completo, telefono, email, activo)
  VALUES (NULLIF(:id_usuario, 0), :codigo_herrador, :nombre_completo, :telefono, LOWER(:email), NVL(:activo, 'SI'));
  :status_code := 201;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'herradores/:id',
    p_method      => 'PUT',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  UPDATE herradores_finasangre
     SET id_usuario = NULLIF(:id_usuario, 0),
         codigo_herrador = :codigo_herrador,
         nombre_completo = :nombre_completo,
         telefono = :telefono,
         email = LOWER(:email),
         activo = NVL(:activo, activo)
   WHERE id_herrador = :id;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'herradores/:id',
    p_method      => 'DELETE',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  DELETE FROM herradores_finasangre WHERE id_herrador = :id;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );
END;
/

BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'herrajes',
    p_method      => 'GET',
    p_source_type => 'json/query',
    p_source      => 'SELECT * FROM herrajes_finasangre ORDER BY NVL(fecha_herraje, SYSDATE) DESC, id_herraje DESC'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'herrajes',
    p_method      => 'POST',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  INSERT INTO herrajes_finasangre (
    id_caballo, id_herrador, id_corral, tipo_herraje,
    fecha_herraje, foto_antes_url, foto_despues_url, observaciones
  ) VALUES (
    :id_caballo, :id_herrador, :id_corral, :tipo_herraje,
    CASE
      WHEN :fecha_herraje IS NULL THEN NULL
      ELSE TO_DATE(SUBSTR(:fecha_herraje, 1, 16), 'YYYY-MM-DD"T"HH24:MI')
    END,
    :foto_antes_url, :foto_despues_url, :observaciones
  );
  :status_code := 201;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'herrajes/:id',
    p_method      => 'PUT',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  UPDATE herrajes_finasangre
     SET id_caballo = :id_caballo,
         id_herrador = :id_herrador,
         id_corral = :id_corral,
         tipo_herraje = :tipo_herraje,
         fecha_herraje = CASE
           WHEN :fecha_herraje IS NULL THEN fecha_herraje
           ELSE TO_DATE(SUBSTR(:fecha_herraje, 1, 16), 'YYYY-MM-DD"T"HH24:MI')
         END,
         observaciones = :observaciones,
         foto_antes_url = :foto_antes_url,
         foto_despues_url = :foto_despues_url
   WHERE id_herraje = :id;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'herrajes/:id',
    p_method      => 'DELETE',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  DELETE FROM herrajes_finasangre WHERE id_herraje = :id;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );
END;
/

BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'usuarios',
    p_method      => 'GET',
    p_source_type => 'json/query',
    p_source      => 'SELECT * FROM usuarios_finasangre ORDER BY nombre_completo'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'usuarios',
    p_method      => 'POST',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  INSERT INTO usuarios_finasangre (nombre_completo, email, telefono, password_hash, rol, activo)
  VALUES (:nombre_completo, LOWER(:email), :telefono, :password_hash, UPPER(:rol), NVL(:activo, 'SI'));
  :status_code := 201;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'usuarios/:id',
    p_method      => 'PUT',
    p_source_type => 'plsql/block',
    p_source      => q'~
DECLARE
  l_email usuarios_finasangre.email%TYPE;
BEGIN
  SELECT LOWER(email)
    INTO l_email
    FROM usuarios_finasangre
   WHERE id_usuario = :id;

  IF l_email = 'abrahambc'
     AND (UPPER(NVL(:activo, 'SI')) <> 'SI'
          OR UPPER(NVL(:rol, 'OWNER')) <> 'OWNER') THEN
    RAISE_APPLICATION_ERROR(-20021, 'No se puede desactivar ni quitar rol OWNER a abrahambc.');
  END IF;

  UPDATE usuarios_finasangre
     SET nombre_completo = :nombre_completo,
         email = LOWER(:email),
         telefono = :telefono,
         password_hash = :password_hash,
         rol = UPPER(:rol),
         activo = NVL(:activo, activo)
   WHERE id_usuario = :id;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'usuarios/:id',
    p_method      => 'DELETE',
    p_source_type => 'plsql/block',
    p_source      => q'~
DECLARE
  l_email usuarios_finasangre.email%TYPE;
BEGIN
  SELECT LOWER(email)
    INTO l_email
    FROM usuarios_finasangre
   WHERE id_usuario = :id;

  IF l_email = 'abrahambc' THEN
    RAISE_APPLICATION_ERROR(-20020, 'No se puede eliminar el OWNER abrahambc.');
  END IF;

  DELETE FROM usuarios_finasangre WHERE id_usuario = :id;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );
END;
/

BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'suscripciones',
    p_method      => 'GET',
    p_source_type => 'json/query',
    p_source      => 'SELECT * FROM suscripciones_finasangre ORDER BY anio DESC, mes DESC'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'suscripciones',
    p_method      => 'POST',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  INSERT INTO suscripciones_finasangre (id_usuario, mes, anio, estado, fecha_limite_pago, pagado)
  VALUES (
    :id_usuario, :mes, :anio, :estado,
    CASE
      WHEN :fecha_limite_pago IS NULL THEN NULL
      ELSE TO_DATE(SUBSTR(:fecha_limite_pago, 1, 10), 'YYYY-MM-DD')
    END,
    :pagado
  );
  :status_code := 201;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'suscripciones/:id',
    p_method      => 'PUT',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  UPDATE suscripciones_finasangre
     SET id_usuario = :id_usuario,
         mes = :mes,
         anio = :anio,
         estado = :estado,
         fecha_limite_pago = CASE
           WHEN :fecha_limite_pago IS NULL THEN NULL
           ELSE TO_DATE(SUBSTR(:fecha_limite_pago, 1, 10), 'YYYY-MM-DD')
         END,
         pagado = :pagado
   WHERE id_suscripcion = :id;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'suscripciones/:id',
    p_method      => 'DELETE',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  DELETE FROM suscripciones_finasangre WHERE id_suscripcion = :id;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );
END;
/

BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'reportes',
    p_method      => 'GET',
    p_source_type => 'json/query',
    p_source      => 'SELECT * FROM reportes_mensuales_finasangre ORDER BY fecha_creacion DESC'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'reportes/generar',
    p_method      => 'POST',
    p_source_type => 'plsql/block',
    p_source      => q'~
DECLARE
  l_inicio DATE := TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM');
  l_fin    DATE := LAST_DAY(ADD_MONTHS(SYSDATE, -1));
  l_mes    NUMBER := EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE, -1));
  l_anio   NUMBER := EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -1));
  l_total  NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_total
    FROM herrajes_finasangre
   WHERE id_herrador = :id_herrador
     AND TRUNC(NVL(
           fecha_herraje,
           CASE
             WHEN anio > 0 AND mes > 0 AND dia > 0
             THEN TO_DATE(anio || '-' || mes || '-' || dia, 'YYYY-MM-DD')
           END
         )) BETWEEN l_inicio AND l_fin;

  MERGE INTO reportes_mensuales_finasangre r
  USING (
    SELECT :id_herrador id_herrador, l_mes mes, l_anio anio FROM dual
  ) s
  ON (
    r.id_herrador = s.id_herrador
    AND r.mes = s.mes
    AND r.anio = s.anio
    AND r.tipo_reporte = 'HERRADOR'
  )
  WHEN NOT MATCHED THEN INSERT (
    id_herrador, periodo_inicio, periodo_fin, mes, anio,
    total_herrajes, estado, tipo_reporte
  ) VALUES (
    :id_herrador, l_inicio, l_fin, l_mes, l_anio,
    l_total, 'GENERADO', 'HERRADOR'
  );

  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'reportes/generar-todos',
    p_method      => 'POST',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  PRC_GENERAR_REPORTES_MENSUALES_FIN;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );
END;
/

BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'aura_finasangre',
    p_method      => 'GET',
    p_source_type => 'json/query',
    p_source      => 'SELECT * FROM aura_finasangre ORDER BY fecha_creacion'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'aura_finasangre',
    p_method      => 'POST',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  INSERT INTO aura_finasangre (
    id_usuario, tipo, mensaje, respuesta, contexto, id_referencia, fecha_creacion
  ) VALUES (
    :id_usuario, :tipo, :mensaje, :respuesta, :contexto, :id_referencia, SYSTIMESTAMP
  );
  :status_code := 201;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );

  ORDS.DEFINE_HANDLER(
    p_module_name => 'finasangre',
    p_pattern     => 'aura_finasangre/limpiar',
    p_method      => 'POST',
    p_source_type => 'plsql/block',
    p_source      => q'~
BEGIN
  DELETE FROM aura_finasangre WHERE id_usuario = :id_usuario;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.P('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 400;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.P('{"success":false,"message":"' || fn_finasangre_json_escape(SQLERRM) || '"}');
END;
~'
  );
END;
/

BEGIN
  MERGE INTO usuarios_finasangre u
  USING (
    SELECT 'abrahambc' email,
           'Abraham BC' nombre_completo,
           'albc300896' password_hash,
           'OWNER' rol,
           'SI' activo
      FROM dual
  ) s
  ON (LOWER(u.email) = s.email)
  WHEN MATCHED THEN UPDATE SET
    u.rol = s.rol,
    u.activo = s.activo,
    u.password_hash = s.password_hash
  WHEN NOT MATCHED THEN INSERT (
    nombre_completo, email, telefono, password_hash, rol, activo
  ) VALUES (
    s.nombre_completo, s.email, '', s.password_hash, s.rol, s.activo
  );
END;
/

-- Limpieza opcional de datos demo. Descomentar solo si corresponde.
-- BEGIN
--   DELETE FROM caballos_finasangre WHERE UPPER(nombre_caballo) IN ('TIGER CAT');
--   DELETE FROM usuarios_finasangre WHERE UPPER(nombre_completo) IN ('JUAN PEREZ', 'JUAN PÉREZ');
--   DELETE FROM corrales_finasangre WHERE UPPER(nombre_corral) = 'CORRAL PRINCIPAL';
-- END;
-- /

BEGIN
  COMMIT;
END;
/
